;; automatically remove old backup files
(defun delete-old-backups()
  (interactive)
  (message "Deleting old backup files...")
  (let ((week (* 60 60 24 7))
        (current (float-time (current-time))))
    (dolist (file (directory-files temporary-file-directory t))
      (when (and (backup-file-name-p file)
                 (> (- current (float-time (fifth (file-attributes file))))
                    week))
        (message file)
        (delete-file file))))
  (message "Old backups deleted."))

(delete-old-backups)
