(use-package ace-jump-mode)
(use-package ace-jump-zap)
(use-package aggressive-indent)
(use-package bm)
(use-package camcorder)
(use-package chronos)
(use-package company)
(use-package company-emoji)
(use-package csharp-mode)
(use-package css-eldoc)
(use-package dash)
(use-package dirtree)
(use-package edit-server)
(use-package eimp)
(use-package elmacro)
(use-package emr)
(use-package exec-path-from-shell)
(use-package f)
(use-package feature-mode)
(use-package fill-column-indicator)
(use-package fiplr)
(use-package fireplace)
(use-package go-mode)
(use-package google-maps)
(use-package google-this)
(use-package google-translate)
(defun google-translate-json-suggestion (json)
  "Retrieve from JSON (which returns by the
`google-translate-request' function) suggestion. This function
does matter when translating misspelled word. So instead of
translation it is possible to get suggestion."
  (let ((info (aref json 7)))
    (if (and info (> (length info) 0))
        (aref info 1)
      nil)))
(defun google-translate-at-point-replace-text ()
  "Translate at point while replacing the text."
  (interactive)
  (when (region-active-p)
    (let ((beginning (region-beginning))
          (end (region-end))
          (google-translate-output-destination 'current-buffer))
      (google-translate-at-point)
      (kill-region beginning end))))
(use-package goto-last-change)
(use-package hookify)
(use-package howdoi)
(use-package htmlize)
(use-package impatient-mode)
(use-package indent-guide)
(use-package ini-mode)
(use-package js2-mode)
(use-package json-mode)
(use-package key-chord)
(use-package less-css-mode)
(use-package litable)
(use-package macrostep)
(use-package make-color)
(use-package markdown-mode)
(use-package miniedit)
(use-package minimap)
(use-package neotree)
(use-package nginx-mode)
(use-package nix-mode
  :mode "\\.nix\\'")
(use-package nsis-mode)
(use-package ox-impress-js)
(use-package ox-ioslide)
(use-package package+)
(use-package package-utils)
(use-package paradox)
(use-package pkg-info)
(use-package powershell
  :custom (powershell-indent 2))
(use-package pretty-symbols)
(use-package rails-log-mode)
(use-package rainbow-mode)
(use-package refine)
(use-package request)
(use-package restclient)
(use-package rtags)
(use-package s)
(use-package shell-pop)
(use-package suggest)
(use-package sunshine)
(use-package switch-window)
(use-package systemd)
(use-package tabbar)
(use-package tagedit)
(use-package textile-mode)
(use-package yari)
